import requests
import re
import json
from urllib.parse import urlparse
from datetime import datetime
import os

# 定义广告过滤器URL列表
URL_LIST = [
"https://github.com/romainmarcoux/malicious-domains/raw/refs/heads/main/full-domains-aa.txt",
"https://github.com/romainmarcoux/malicious-domains/raw/refs/heads/main/full-domains-ab.txt",
"https://github.com/romainmarcoux/malicious-domains/raw/refs/heads/main/full-domains-ac.txt",
"https://raw.githubusercontent.com/xxcriticxx/.pl-host-file/master/hosts.txt",
"http://malc0de.com/bl/IP_Blacklist.txt",
"http://mirror1.malwaredomains.com/files/justdomains",
"https://hosts.ubuntu101.co.za/badips.txt",
"https://raw.githubusercontent.com/smed79/blacklist/master/extra/nsfw.txt",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts",
"https://zerodot1.gitlab.io/CoinBlockerLists/list.txt",
"https://pgl.yoyo.org/as/serverlist.php?hostformat=hosts;showintro=0",
"http://www.malwaredomainlist.com/hostslist/hosts.txt",
"https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
"https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset",
"http://sysctl.org/cameleon/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts",
"https://raw.githubusercontent.com/michaeltrimm/hosts-blocking/master/_hosts.txt",
"http://someonewhocares.org/hosts/zero/hosts",
"https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt",
"http://www.badips.com/get/list/any/4?age=12",
"http://www.badips.com/get/list/any/3?age=12",
"https://raw.githubusercontent.com/smed79/blacklist/master/hosts.txt",
"https://github.com/mitchellkrogza/Suspicious.Snooping.Sniffing.Hacking.IP.Addresses/blob/master/ips.list",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
"https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
"https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/PULL_REQUESTS/domains.txt",
"https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/blob/master/hacked-domains.list",
"https://raw.githubusercontent.com/yous/YousList/master/hosts.txt",
"https://raw.githubusercontent.com/mitchellkrogza/Top-Attacking-IP-Addresses-Against-Wordpress-Sites/master/wordpress-attacking-ips.txt",
"https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt",
"https://gitlab.com/Wiggum27/blockers/-/raw/master/hosts",
"https://gitlab.com/ZeroDot1/CoinBlockerLists/raw/master/list_browser.txt",
"https://v.firebog.net/hosts/static/w3kbl.txt",
"http://www.badips.com/get/list/any/5?age=12",
"https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/malware.list",
"https://raw.githubusercontent.com/Yhonay/antipopads/master/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts",
"https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt",
"https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/raw/refs/heads/master/domains/domains0.list",
"https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/raw/refs/heads/master/domains/domains1.list",
"https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/raw/refs/heads/master/domains/domains2.list",
"https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/raw/refs/heads/master/domains/domains3.list",
"https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/raw/refs/heads/master/domains/domains4.list",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/adult-themed/adblock.txt",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/bogons/plain.black.ipcidr.list",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/chris/autodiscovery.list",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/chris/bad.abuse.list",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/crypto/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/doh/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/easylist/adblock.txt",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/family-safe/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/gambling/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/games/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/google/adblock.txt",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/malicious-dom/adblock.txt",
"https://github.com/cbuijs/accomplist/raw/refs/heads/main/malicious-ip/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/school/adblock.txt",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/spamhaus/plain.black.ipcidr.list",
"https://raw.githubusercontent.com/cbuijs/accomplist/refs/heads/main/streaming/adblock.txt",
"https://raw.githubusercontent.com/C24Be/AS_Network_List/refs/heads/main/blacklists/blacklist_with_comments.txt",
"https://raw.githubusercontent.com/liyiecho/Foreign_IPv6_DNS_Blacklist/refs/heads/main/Foreign_IPv6_DNS_Blacklist.txt",
"https://raw.githubusercontent.com/wifimedia/wificode/refs/heads/master/hardware_active",
"https://raw.githubusercontent.com/Kdroidwin/uBlacklist-filter-by-kdroidwin/refs/heads/main/uBlacklist.txt",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/adult/domains.24733",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/bank/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/bitcoin/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/blog/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/celebrity/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cooking/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cryptojacking/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/fakenews/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/dating/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/doh/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/download/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/filehosting/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/gambling/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/games/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/jobsearch/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/lingerie/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/liste_blanche/domains",
"https://github.com/olbat/ut1-blacklists/raw/refs/heads/master/blacklists/malware/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/manga/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/marketingware/domains",
"https://github.com/olbat/ut1-blacklists/raw/refs/heads/master/blacklists/phishing/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/press/domainshttps://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/publicite/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/radio/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/press/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/redirector/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/remote-control/domains",
"https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/residential-proxies/domains",
"https://github.com/miriquidi/domain-blocklists/raw/refs/heads/main/block.txt",
"https://raw.githubusercontent.com/eallion/uBlacklist-subscription-compilation/refs/heads/main/uBlacklist.txt",
"https://raw.githubusercontent.com/insomnimus/seo-garbage/refs/heads/main/list.txt",
"https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt",
"https://abpvn.com/android/abpvn.txt",
"https://adaway.org/hosts.txt",
"https://adblock.mahakala.is",
"https://asc.hk/adplus.txt",
"https://assets.windscribe.com/custom_blocklists/clickbait.txt",
"https://badmojr.github.io/1Hosts/Lite/domains.txt",
"https://badmojr.github.io/1Hosts/Pro/domains.txt",
"#https://badmojr.github.io/1Hosts/Xtra/domains.txt",
"http://sbc.io/hosts/hosts",
"https://big.oisd.nl/",
"https://blokada.org/blocklists/exodusprivacy/standard/hosts.txt",
"https://codeberg.org/spootle/blocklist/raw/branch/master/blocklist.txt",
"https://dehakkelaar.nl/lists/cryptojacking_campaign.list.txt",
"https://getadhell.com/standard-package.txt",
"https://get.domainsblacklists.com/blacklist.txt",
"https://gist.githubusercontent.com/anthony-wang/943e08bc83759e1dbb8745819f4b3eca/raw/8744f04cfc3f8614aabc42ff2915afe60ee3df13/spotify-hosts.txt",
"https://gist.githubusercontent.com/BBcan177/4a8bf37c131be4803cb2/raw/343ff780e15205b4dd0de37c86af34cfb26b2fbe/MS-2",
"https://gist.githubusercontent.com/BBcan177/b6df57cef74e28d90acf1eec93d62d3b/raw/f0996cf5248657ada2adb396f3636be8716b99eb/MS-4",
"https://gist.githubusercontent.com/hkamran80/779019103fcd306979411d44c8d38459/raw/5d5a2950777b9c1ea88d1e7ae5db921b300d9c39/SmartTV2.txt",
"https://gist.githubusercontent.com/MOxFIVE/4730cac715ef406bd8eac7b29335be4a/raw/d21fa08e97963edde372d0d3e50703c783c9c32e/Personal%2520Blocklist.txt",
"https://gist.githubusercontent.com/mrprobot/257f3af652c0b4599634c7c063ec2d88/raw/d4932cc89a94d9a389da1513b4b31437c27bc69e/Spotify_Eliminate_Advertisements",
"https://gist.githubusercontent.com/opus-x/3e673a9d5db2a214df05929a4eee6a57/raw/8b9085ea74be4a36aa1348bfe6af7135bafb6ea1/Spotify_Eliminate_Advertisements",
"https://gist.githubusercontent.com/rifkyekayama/f7c43e470f23878b20416e68f73829dc/raw/46e8c6b806e9f75b49c2683b313d08e1d1138cbe/spotihosts",
"https://gist.githubusercontent.com/Shujito/b7a8f8f971b22f49b4313d7d3e8e6931/raw/4a37da8edb85f218103e7c5abbaccba5ec23cceb/spotihosts",
"https://gist.githubusercontent.com/vuxat/f25149898451efc6a2723af7c6643f82/raw/5985279ee61a7a77d4f5a5163460177b6a8b62e2/hosts-file.net_hjk.txt",
"https://gist.githubusercontent.com/wassname/b594c63222f9e4c83ea23c818440901b/raw/1b0afd2aecf3a099f1681b1cf18fc0e6e2fa116a/Samsung%2520Smart-TV%2520Blocklist%2520Adlist%2520(for%2520PiHole)",
"https://gist.githubusercontent.com/wesinator/7f40d954a2fec693c358b030a6d6c971/raw/f7164b0ea8af8b4a1655c7ff426777abd57d60f9/Mandiant_APT1_Domains.txt",
"https://git.herrbischoff.com/trackers/plain/cookie.txt",
"https://git.herrbischoff.com/trackers/plain/domains.txt",
"https://git.herrbischoff.com/trackers/plain/telemetry.txt",
"https://git.herrbischoff.com/trackers/plain/trackers.txt",
"https://github.com/badmojr/1Hosts/releases/download/latest/1hosts-Lite_domains.txt",
"https://github.com/badmojr/1Hosts/releases/download/latest/1hosts-Pro_domains.txt",
"https://github.com/What-Zit-Tooya/Ad-Block/blob/main/Main-Blocklist/Ad-Block-HOSTS.txt",
"https://gitlab.com/curben/phishing-filter/raw/master/dist/phishing-filter-hosts.txt",
"https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-domains.txt",
"https://gitlab.com/Kurobeats/phishing_hosts/raw/master/hosts",
"https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt",
"https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/notrack-malware.txt",
"https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt",
"https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/Individual%20lists/The_Quantum_Youtube-Ads-List.txt",
"https://gitlab.com/The_Quantum_Alpha/the-quantum-ad-list/-/raw/master/Raw/The_Quantum_Ad-List.txt",
"https://gitlab.com/Wiggum27/blockers/-/raw/master/hosts",
"https://gitlab.com/Wiggum27/blockers/-/raw/master/host.txt",
"https://gitlab.com/Wiggum27/blockers/-/raw/master/NetguardHosts",
"https://gitlab.com/Wiggum27/blockers/-/raw/master/NetguardHosts.txt",
"https://hblock.molinero.dev/hosts",
"https://hole.cert.pl/domains/domains.txt",
"https://hostfiles.frogeye.fr/firstparty-only-trackers-hosts.txt",
"https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt",
"https://hostfiles.frogeye.fr/multiparty-only-trackers-hosts.txt",
"https://hostfiles.frogeye.fr/multiparty-only-trackers.txt",
"https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt",
"https://hostfiles.frogeye.fr/multiparty-trackers.txt",
"https://hostsfile.mine.nu/hosts0.txt",
"https://hostsfile.org/Downloads/hosts.txt",
"https://hosts.ubuntu101.co.za/domains.list",
"https://logroid.github.io/adaway-hosts/hosts.txt",
"https://malwaredomains.usu.edu/domains.hosts",
"https://malwaredomains.usu.edu/immortal_domains.txt",
"https://malwaredomains.usu.edu/justdomains",
"https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt",
"https://o0.pages.dev/Lite/domains.txt",
"https://o0.pages.dev/Pro/domains.txt",
"#https://o0.pages.dev/Xtra/domains.txt",
"http://someonewhocares.org/hosts/zero/hosts",
"https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt",
"https://pgl.yoyo.org/adservers/serverlist.php?hostformat=nohtml&showintro=0&mimetype=plaintext",
"https://phishing.army/download/phishing_army_blocklist_extended.txt",
"https://phishing.army/download/phishing_army_blocklist.txt",
"https://raw.githubusercontent.com/12425/adblist/master/adbhost.txt",
"https://raw.githubusercontent.com/34730/Adaway/master/block",
"https://raw.githubusercontent.com/abc45628/hosts/master/hosts",
"https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt",
"https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads_justdomains.txt",
"https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_clickthroughs_justdomains.txt",
"https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_microsites_justdomains.txt",
"https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers_justdomains.txt",
"https://raw.githubusercontent.com/AdroitAdorKhan/EnergizedProtection/master/core/hosts",
"https://raw.githubusercontent.com/AdroitAdorKhan/EnergizedProtection/master/core/hosts-xtreme",
"https://raw.githubusercontent.com/aleclee/DNS-Blacklists/master/AdHosts.txt",
"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/domains.txt",
"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v2_domains.txt",
"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v3_domains.txt",
"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_domains.txt",
"https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-07-18_nso/v4_validation_domains.txt",
"https://raw.githubusercontent.com/angelics/pfbng/master/ads/ads-domain-list.txt",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/CoinMiner.txt",
"https://raw.githubusercontent.com/arcetera/Minimal-Hosts-Blocker/master/etc/MinimalHostsBlocker/minimalhosts",
"https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts",
"https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt",
"https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt",
"https://raw.githubusercontent.com/badmojr/1Hosts/master/Pro/domains.txt",
"#https://raw.githubusercontent.com/badmojr/1Hosts/master/Xtra/domains.txt",
"https://raw.githubusercontent.com/bentasker/adblocklists/master/config/manualblocks/00_general.txt",
"https://raw.githubusercontent.com/bentasker/adblocklists/master/config/manualblocks/admiral-antiadblock.txt",
"https://raw.githubusercontent.com/bentasker/adblocklists/master/config/manualblocks/xiaomi.txt",
"https://raw.githubusercontent.com/bentasker/adblocklists/master/config/manualzones.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/filters/adservers-all.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/filters/adservers.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/domain.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/adservers-all.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/adservers-extra.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/hosts-extra.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/hosts-group.txt",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/source/hosts.txt",
"https://raw.githubusercontent.com/biroloter/Mobile-Ad-Hosts/master/hosts",
"https://raw.githubusercontent.com/bjornstar/hosts/master/hosts",
"https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Regular%20Hosts.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/abuse.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/ads.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/fraud.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/malware.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/ransomware.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/scam.txt",
"https://raw.githubusercontent.com/blocklistproject/Lists/master/tracking.txt",
"https://raw.githubusercontent.com/blocktastic/pihole/master/blocktastic.txt",
"https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final.hosts",
"https://raw.githubusercontent.com/buckmelanoma/block_lists/master/leadforensics.txt",
"https://raw.githubusercontent.com/cb-software/CB-Malicious-Domains/master/block_lists/domains_only.txt",
"https://raw.githubusercontent.com/cb-software/CB-Malicious-Domains/master/block_lists/hosts",
"https://raw.githubusercontent.com/cchevy/macedonian-pi-hole-blocklist/master/hosts.txt",
"https://raw.githubusercontent.com/chrisjudk/hosts/master/hosts",
"https://raw.githubusercontent.com/CitizenXVIL/Hosts/master/mobile%20domains.txt",
"https://raw.githubusercontent.com/CitizenXVIL/Hosts/master/Youtube%20hosts.txt",
"https://raw.githubusercontent.com/craiu/mobiletrackers/master/list.txt",
"#https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt",
"https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt",
"#https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt",
"https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Android/androidblocklist.txt",
"https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/MobileAppAds/appadsblocklist.txt",
"https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/SmartTV/smarttvblocklist.txt",
"https://raw.githubusercontent.com/d43m0nhLInt3r/socialblocklists/master/Tracking/trackingblocklist.txt",
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt",
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AncientLibrary/gmbkslist%20%28Hosts%29.txt",
"https://raw.githubusercontent.com/DataMaster-2501/DataMaster-Android-AdBlock-Hosts/master/hosts",
"https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt",
"https://raw.githubusercontent.com/desbma/referer-spam-domains-blacklist/master/spammers.txt",
"https://raw.githubusercontent.com/DK-255/Pi-hole-list-1/main/Ads-Blocklist",
"https://raw.githubusercontent.com/doadin/Pi-Hole-Blocklist/main/block.list",
"https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/activation.txt",
"https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/adservers-and-trackers.txt",
"https://raw.githubusercontent.com/DRSDavidSoft/additional-hosts/master/domains/blacklist/fake-domains.txt",
"#https://raw.githubusercontent.com/durablenapkin/block/master/home-heavy.txt",
"#https://raw.githubusercontent.com/durablenapkin/block/master/home-lite.txt",
"#https://raw.githubusercontent.com/durablenapkin/block/master/home-medium.txt",
"#https://raw.githubusercontent.com/durablenapkin/block/master/home-obese.txt",
"https://raw.githubusercontent.com/durablenapkin/block/master/luminati.txt",
"https://raw.githubusercontent.com/durablenapkin/block/master/streaming.txt",
"https://raw.githubusercontent.com/durablenapkin/block/master/tvstream.txt",
"https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt",
"https://raw.githubusercontent.com/dylanarmstrong/hosts/master/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/antipopads-re/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/rlwpx.free.fr.hrsk/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/rlwpx.free.fr.htrc/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts",
"https://raw.githubusercontent.com/faralai/Pihole-Rules/master/Fara-Popups_Head",
"https://raw.githubusercontent.com/faralai/Pihole-Rules/master/Fara-Xiaomi-info",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/hola-luminati-full-block.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/huawei-trackers.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smartphone-ads-tracking.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/smart-tv-ads-tracking.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/spotify-ads-tracking.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/windows10-spying-erm-i-mean-telemetry-lol.txt",
"https://raw.githubusercontent.com/ftpmorph/ftprivacy/master/blocklists/xiaomi-ads-tracking.txt",
"https://raw.githubusercontent.com/genediazjr/nopelist/master/nopelist.txt",
"https://raw.githubusercontent.com/greatis/Anti-WebMiner/master/blacklist.txt",
"https://raw.githubusercontent.com/gwillem/magento-malware-scanner/master/rules/burner-domains.txt",
"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.mini.txt",
"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt",
"https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/COVID%20-%2019%20Malicious%20Domains",
"https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/DNS-BH%20Malware%20Domains%20List",
"https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Malware%20Domain%20List",
"https://raw.githubusercontent.com/Hariharann8175/Indicators-of-Compromise-IOC-/master/Ransomware%20URL%27s",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/evil-domains.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Advertisements.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/IP%20Loggers.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Other.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Phishing.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Scams.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Shockers.txt",
"https://raw.githubusercontent.com/hell-sh/Evil-Domains/master/lists/Trackers.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/advertisement.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/fraudulent.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/malware.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/phishing.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/ransomware.txt",
"https://raw.githubusercontent.com/hemiipatu/PiHoleBlocklists/master/blocklists/scam.txt",
"https://raw.githubusercontent.com/HenningVanRaumle/HHadlist/main/hhadlist",
"https://raw.githubusercontent.com/herndlm/hosts_merge/master/hosts_blacklist.txt",
"https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt",
"https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt",
"https://raw.githubusercontent.com/infinitytec/blocklists/master/ads-and-trackers.txt",
"https://raw.githubusercontent.com/infinitytec/blocklists/master/possibilities.txt",
"https://raw.githubusercontent.com/infinitytec/blocklists/master/scams-and-phishing.txt",
"https://raw.githubusercontent.com/jakdev121/AMS2/master/pi_indo_ads.txt",
"https://raw.githubusercontent.com/jakejarvis/ios-trackers/master/blocklist.txt",
"https://raw.githubusercontent.com/jaykepeters/Blocklists/master/Ads/spotify.txt",
"https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/GoodbyeAds-Database.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-1.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-2.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-3.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-4.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-5.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-6.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-7.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-8.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Core/YouTube/YoutubeAdblock-9.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-LeEco-Extension.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Samsung-AdBlock.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Spotify-AdBlock.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-Xiaomi-Extension.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt",
"https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt",
"https://raw.githubusercontent.com/jkrejcha/AdmiraList/master/AdmiraList.txt",
"https://raw.githubusercontent.com/JoseGalRe/Hosty/master/bits/hosty.blacklist",
"https://raw.githubusercontent.com/justdomains/blocklists/master/lists/adguarddns-justdomains.txt",
"https://raw.githubusercontent.com/justdomains/blocklists/master/lists/easylist-justdomains.txt",
"https://raw.githubusercontent.com/justdomains/blocklists/master/lists/easyprivacy-justdomains.txt",
"https://raw.githubusercontent.com/justdomains/blocklists/master/lists/nocoin-justdomains.txt",
"https://raw.githubusercontent.com/kang49/kang49regexblacklistproject/main/blacklist",
"https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list",
"https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/crowed_list.txt",
"https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt",
"https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_badbait_th.txt",
"https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_google_adservice_id.txt",
"https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover_aggressive.txt",
"https://raw.githubusercontent.com/kowith337/PersonalFilterListCollection/master/hosts/hosts_leftover.txt",
"https://raw.githubusercontent.com/KurzGedanke/kurzBlock/master/kurzBlock.txt",
"https://raw.githubusercontent.com/Laicure/HostsY_hosts/master/shithosts",
"https://raw.githubusercontent.com/Lerist/Go-Hosts/master/hosts-ad",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/apple-telemetry",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/blacklist",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/microsoft-telemetry",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/old/spotify-addl",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/streaming-hosts",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/tiktok-hosts",
"https://raw.githubusercontent.com/liamengland1/mischosts/master/whiteops-hosts",
"https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/ads-and-tracking-extended.txt",
"https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/tracking-aggressive-extended.txt",
"https://raw.githubusercontent.com/ligyxy/Blocklist/master/BLOCKLIST",
"https://raw.githubusercontent.com/logroid/adaway-hosts/master/hosts.txt",
"https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt",
"https://raw.githubusercontent.com/mayesidevel/PiHoleLists/master/MiscBlocklist",
"https://raw.githubusercontent.com/meinhimmel/hosts/master/hosts",
"https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt",
"https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/custom-blocklist.txt",
"https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_ads.txt",
"https://raw.githubusercontent.com/michaeltrimm/hosts-blocking/master/_hosts.txt",
"https://raw.githubusercontent.com/migueldemoura/ublock-umatrix-rulesets/master/Hosts/ads-tracking",
"https://raw.githubusercontent.com/migueldemoura/ublock-umatrix-rulesets/master/Hosts/ads-tracking-breaking",
"https://raw.githubusercontent.com/migueldemoura/ublock-umatrix-rulesets/master/Hosts/malware",
"https://raw.githubusercontent.com/minoplhy/filters/main/Resources/blocked.txt",
"https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts",
"https://raw.githubusercontent.com/mitchellkrogza/CoinBlockerLists/refs/heads/master/hosts",
"https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt",
"https://raw.githubusercontent.com/mitchellkrogza/Stop.Google.Analytics.Ghost.Spam.HOWTO/master/output/domains/ACTIVE/list",
"https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list",
"https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/domains0.list",
"https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/domains1.list",
"https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/domains2.list",
"https://raw.githubusercontent.com/mitchellkrogza/Ultimate.Hosts.Blacklist/master/domains/domains3.list",
"#https://raw.githubusercontent.com/mkb2091/blockconvert/master/internal/blocklist.txt",
"#https://raw.githubusercontent.com/mkb2091/blockconvert/master/output/domains.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/_blocklist",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/melcosoft.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/old%3F/miui_zero.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/old%3F/rom.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/resabuse.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/rom.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/tikkok.txt",
"https://raw.githubusercontent.com/monolit/fuckhosts/main/wot.txt",
"#https://raw.githubusercontent.com/muxcc/AdsBlockLists/master/aumm.hosts",
"https://raw.githubusercontent.com/muxcc/AdsBlockLists/master/ksn.hosts",
"https://raw.githubusercontent.com/muxcc/AdsBlockLists/master/smart-tv.hosts",
"#https://raw.githubusercontent.com/muxcc/AdsBlockLists/master/spy.hosts",
"https://raw.githubusercontent.com/muxcc/AdsBlockLists/master/xiaomi.hosts",
"https://raw.githubusercontent.com/nathanaccidentally/SystemHostsBlocker/master/hosts",
"https://raw.githubusercontent.com/Neo23x0/signature-base/master/iocs/c2-iocs.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/basic/hijack/others.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/2345.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/analytics.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/coinhave.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/imrworldwide.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/popup/1.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/popup/2.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/popup/3.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/data/_data/extra/popup/common.txt",
"https://raw.githubusercontent.com/neoFelhz/neohosts/gh-pages/basic/hosts",
"https://raw.githubusercontent.com/neoFelhz/neohosts/gh-pages/full/hosts",
"https://raw.githubusercontent.com/nextdns/cname-cloaking-blocklist/master/domains",
"https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt",
"#https://raw.githubusercontent.com/oneoffdallas/dohservers/master/list.txt",
"https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/blacklist.txt",
"https://raw.githubusercontent.com/p1r473/hosts/master/hosts.txt",
"https://raw.githubusercontent.com/p1r473/pornaway/master/hosts/safe_ads.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-government-malware.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-hphosts-legacy.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-nolovia.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-silverpop.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/hosts-windows-telemetry.txt",
"https://raw.githubusercontent.com/parseword/nolovia/master/skel/personal-blacklist.txt",
"https://raw.githubusercontent.com/paulgb/BarbBlock/master/blocklists/domain-list.txt",
"https://raw.githubusercontent.com/paulgb/BarbBlock/master/blocklists/hosts-file.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SessionReplay.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt",
"https://raw.githubusercontent.com/pirat28/IHateTracker/master/iHateTracker.txt",
"https://raw.githubusercontent.com/piwik/referrer-spam-blacklist/master/spammers.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt",
"https://raw.githubusercontent.com/PoorPocketsMcNewHold/steamscamsite/master/steamscamsite.txt",
"https://raw.githubusercontent.com/PoorPocketsMcNewHold/steamscamsites/master/steamscamsite.txt",
"https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardApps.txt",
"https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt",
"https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt",
"https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileSpyware.txt",
"https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/EasyPrivacy3rdParty.txt",
"https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHostsCB/etc/MinimalHostsBlocker/minimalhosts",
"https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
"https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting2",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting3",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting4",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/MS-Office-Telemetry",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails",
"https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Ads",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Cryptocurrency",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Malware",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Scam",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Tracking",
"https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/master/Lists/Typo",
"https://raw.githubusercontent.com/smed79/blacklist/master/hosts.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/ads.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/affiliate.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/analytics.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/enrichments.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/fake.txt",
"https://raw.githubusercontent.com/soteria-nou/domain-list/cleaned/widgets.txt",
"https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt",
"https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt",
"https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt",
"https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/suspicious/android_pua.txt",
"https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/suspicious/pua.txt",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
"https://raw.githubusercontent.com/svetlyobg/svet-custom-domains/master/ads-domains",
"https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt",
"https://raw.githubusercontent.com/Th3M3/blocklists/master/malware.list",
"https://raw.githubusercontent.com/Th3M3/blocklists/master/tracking%26ads.list",
"https://raw.githubusercontent.com/tiuxo/hosts/master/ads",
"https://raw.githubusercontent.com/TonyRL/blocklist/master/hosts",
"https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/superhosts.deny/superhosts0.deny",
"https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/superhosts.deny/superhosts1.deny",
"https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/superhosts.deny/superhosts2.deny",
"https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/master/superhosts.deny/superhosts3.deny",
"https://raw.githubusercontent.com/UnbendableStraw/samsungnosnooping/master/Samsungnosnooping.txt",
"https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts",
"https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt",
"https://raw.githubusercontent.com/Veticia/antipopads/master/hosts",
"https://raw.githubusercontent.com/vokins/yhosts/master/hosts",
"https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt",
"https://raw.githubusercontent.com/What-Zit-Tooya/Ad-Block/main/Main-Blocklist/Ad-Block-HOSTS.txt",
"https://raw.githubusercontent.com/WillPresley/ZeroDot1_CoinBlockerList/refs/heads/main/hosts",
"https://raw.githubusercontent.com/x0uid/SpotifyAdBlock/master/SpotifyBlocklist.txt",
"https://raw.githubusercontent.com/XionKzn/PiHole-Lists/master/PiHole/Blocklist_HOSTS.txt",
"https://raw.githubusercontent.com/XionKzn/PiHole-Lists/master/PiHole/PiHole_HOSTS_Spyware_HOSTS.txt",
"https://raw.githubusercontent.com/xlimit91/xlimit91-block-list/master/blacklist.txt",
"https://raw.githubusercontent.com/yous/YousList/master/hosts.txt",
"https://raw.githubusercontent.com/zznidar/BAR/master/BAR-list",
"https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
"https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
"https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
"https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt",
"https://small.oisd.nl/",
"https://someonewhocares.org/hosts/zero/hosts",
"https://stopforumspam.com/downloads/toxic_domains_whole.txt",
"https://sysctl.org/cameleon/hosts",
"https://tgc.cloud/downloads/hosts.txt",
"https://theantisocialengineer.com/AntiSocial_Blacklist_Community_V1.txt",
"https://urlhaus.abuse.ch/downloads/hostfile",
"https://v.firebog.net/hosts/AdguardDNS.txt",
"https://v.firebog.net/hosts/Admiral.txt",
"https://v.firebog.net/hosts/Easylist.txt",
"https://v.firebog.net/hosts/Easyprivacy.txt",
"https://v.firebog.net/hosts/neohostsbasic.txt",
"https://v.firebog.net/hosts/Prigent-Ads.txt",
"https://v.firebog.net/hosts/Prigent-Crypto.txt",
"https://v.firebog.net/hosts/Prigent-Malware.txt",
"https://v.firebog.net/hosts/RPiList-Malware.txt",
"https://v.firebog.net/hosts/RPiList-Phishing.txt",
"https://v.firebog.net/hosts/static/w3kbl.txt",
"https://warui.intaa.net/adhosts/hosts.txt",
"https://winhelp2002.mvps.org/hosts.txt",
"https://www.bentasker.co.uk/adblock/blockeddomains.txt",
"https://www.bentasker.co.uk/adblock/blocked_domains_with_sm.txt",
"https://www.bentasker.co.uk/adblock/config/manualblocks/xiaomi.txt",
"https://www.bentasker.co.uk/adblock/config/manualzones.txt",
"https://www.botvrij.eu/data/ioclist.domain.raw",
"https://www.botvrij.eu/data/ioclist.hostname.raw",
"https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt",
"https://www.github.developerdan.com/hosts/lists/tracking-aggressive-extended.txt",
"https://www.stopforumspam.com/downloads/toxic_domains_whole.txt",
"https://www.thedumbterminal.co.uk/files/services/squidblockedsites/blocked.txt",
"https://zonefiles.io/f/compromised/domains/live",
"https://adaway.org/hosts.txt",
"https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt",
"https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt",
"https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
"https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt",
"https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt",
"https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt",
"https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext",
"https://phishing.army/download/phishing_army_blocklist_extended.txt",
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt",
"https://raw.githubusercontent.com/Dawsey21/Lists/master/main-blacklist.txt",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts",
"https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt",
"https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts",
"https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt",
"https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts",
"https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt",
"https://raw.githubusercontent.com/vokins/yhosts/master/hosts",
"https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts",
"https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt",
"https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt",
"https://someonewhocares.org/hosts/zero/hosts",
"https://urlhaus.abuse.ch/downloads/hostfile/",
"https://v.firebog.net/hosts/static/w3kbl.txt",
"https://winhelp2002.mvps.org/hosts.txt",
"https://raw.githubusercontent.com/vincentkenny01/spotblock/master/ondemand",
"https://raw.githubusercontent.com/vincentkenny01/spotblock/master/samsung",
"https://raw.githubusercontent.com/vincentkenny01/spotblock/master/spotify",
"https://raw.githubusercontent.com/vincentkenny01/spotblock/refs/heads/master/minimalhosts",
"https://v.firebog.net/hosts/AdguardDNS.txt",
"https://v.firebog.net/hosts/Admiral.txt",
"https://v.firebog.net/hosts/Easylist-Dutch.txt",
"https://v.firebog.net/hosts/Easylist.txt",
"https://v.firebog.net/hosts/Easyprivacy.txt",
"https://v.firebog.net/hosts/Kowabit.txt",
"https://v.firebog.net/hosts/Prigent-Ads.txt",
"https://v.firebog.net/hosts/Prigent-Adult.txt",
"https://v.firebog.net/hosts/Prigent-Crypto.txt",
"https://v.firebog.net/hosts/Prigent-Malware.txt",
"https://v.firebog.net/hosts/RPiList-Malware.txt",
"https://v.firebog.net/hosts/RPiList-Phishing.txt",
"https://v.firebog.net/hosts/neohostsbasic.txt",
"https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts",
"https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt",
"https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt",
"https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt",
"https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts",
"https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt",
"https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser",
"https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt",
"https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts",
"https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt",
"https://blocklistproject.github.io/Lists/alt-version/abuse-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/ads-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/crypto-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/drugs-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/everything-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/facebook-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/fraud-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/gambling-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/malware-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/phishing-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/ransomware-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/redirect-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/scam-nl.txt",
"https://blocklistproject.github.io/Lists/alt-version/tracking-nl.txt",
"https://gist.githubusercontent.com/opus-x/3e673a9d5db2a214df05929a4eee6a57/raw",
"https://raw.githubusercontent.com/LaurentFough/pihole-youtube-adblock/master/pihole-youtube-adblock.txt",
"https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts",
"https://v.firebog.net/hosts/static/w3kbl.txt",
"https://adaway.org/hosts.txt",
"https://v.firebog.net/hosts/AdguardDNS.txt",
"https://v.firebog.net/hosts/Admiral.txt",
"https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt",
"https://v.firebog.net/hosts/Easylist.txt",
"https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts",
"https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts",
"https://v.firebog.net/hosts/Easyprivacy.txt",
"https://v.firebog.net/hosts/Prigent-Ads.txt",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts",
"https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt",
"https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt",
"https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt",
"https://v.firebog.net/hosts/Prigent-Crypto.txt",
"https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts",
"https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt",
"https://phishing.army/download/phishing_army_blocklist_extended.txt",
"https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt",
"https://v.firebog.net/hosts/RPiList-Malware.txt",
"https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt",
"https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts",
"https://urlhaus.abuse.ch/downloads/hostfile/",
"https://lists.cyberhost.uk/malware.txt",
"https://big.oisd.nl/",
"https://raw.githubusercontent.com/MDP43140/BaDomain/refs/heads/main/BaDomain.txt",
"https://github.com/skyhigh24/BlockList/raw/refs/heads/main/GravityExport.txt",
"https://raw.githubusercontent.com/ph00lt0/blocklist/refs/heads/master/blocklist.txt",
"https://raw.githubusercontent.com/ph00lt0/blocklist/master/blocklist.txt"

]

# 日志文件路径
LOG_FILE = "adblock_log.txt"
OUTPUT_FILE = "adblock_reject14.yaml"  # Mihomo 使用的 YAML 格式

def is_valid_dns_domain(domain):
    """验证域名是否符合DNS规范"""
    if len(domain) > 253:
        return False
    
    labels = domain.split('.')
    for label in labels:
        if not label or len(label) > 63:
            return False
        if not re.match(r"^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$", label):
            return False
    
    tld = labels[-1]
    if not re.match(r"^[a-zA-Z]{2,}$", tld):
        return False
    
    return True

def download_rules(url):
    """下载规则并返回内容"""
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    try:
        response = requests.get(url, headers=headers, timeout=30)
        response.raise_for_status()
        return response.text
    except Exception as e:
        log_message(f"处理 {url} 时出错: {str(e)}")
        return None

def log_message(message):
    """记录日志信息"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"[{timestamp}] {message}\n"
    print(log_line.strip())
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(log_line)

def process_rules():
    """处理所有规则并生成 Mihomo 兼容的规则集"""
    unique_rules = set()
    excluded_domains = set()

    for url in URL_LIST:
        log_message(f"正在处理: {url}")
        content = download_rules(url)
        if not content:
            continue

        for line in content.splitlines():
            line = line.strip()
            if not line or line.startswith('!'):
                continue

            # 处理白名单规则 (@@)
            if line.startswith('@@'):
                domains = re.sub(r'^@@', '', line)
                domains = re.findall(r'[\w.-]+\.[a-zA-Z]{2,}', domains)
                for domain in domains:
                    if is_valid_dns_domain(domain):
                        excluded_domains.add(domain.lower())
                continue

            # 匹配 Adblock/Easylist 格式的规则
            if re.match(r'^\|\|([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\^$', line):
                domain = re.match(r'^\|\|([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})\^$', line).group(1)
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

            # 匹配 Hosts 文件格式的 IPv4 规则
            if re.match(r'^(0\.0\.0\.0|127\.0\.0\.1)\s+([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$', line):
                domain = re.match(r'^(0\.0\.0\.0|127\.0\.0\.1)\s+([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$', line).group(2)
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

            # 匹配 Hosts 文件格式的 IPv6 规则
            if re.match(r'^::(1)?\s+([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$', line):
                domain = re.match(r'^::(1)?\s+([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$', line).group(2)
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

            # 匹配 Dnsmasq address=/域名/格式的规则
            if re.match(r'^address=/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/$', line):
                domain = re.match(r'^address=/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/$', line).group(1)
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

            # 匹配 Dnsmasq server=/域名/的规则
            if re.match(r'^server=/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/$', line):
                domain = re.match(r'^server=/([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/$', line).group(1)
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

            # 处理纯域名行
            if re.match(r'^([a-zA-Z0-9.-]+\.[a-zA-Z]{2,})$', line):
                domain = line
                if is_valid_dns_domain(domain):
                    unique_rules.add(domain.lower())
                continue

    # 排除白名单中的域名
    final_rules = [domain for domain in unique_rules if domain not in excluded_domains]
    final_rules = sorted(final_rules)

    # 生成 Mihomo 兼容的 YAML 规则集
    mihomo_ruleset = {
        "payload": final_rules
    }

    # 写入 YAML 文件
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Title: AdBlock Rule For Mihomo\n")
        f.write("# Description: 适用于Mihomo的域名拦截规则集\n")
        f.write("# Generated: {}\n".format(datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
        f.write("# Rule Count: {}\n".format(len(final_rules)))
        f.write("payload:\n")
        for domain in final_rules:
            f.write(f"  - '{domain}'\n")

    log_message(f"生成的有效规则总数: {len(final_rules)}")
    log_message(f"规则集已保存到: {os.path.abspath(OUTPUT_FILE)}")

if __name__ == "__main__":
    # 初始化日志文件
    with open(LOG_FILE, "w", encoding="utf-8") as f:
        f.write("AdBlock Rule Generator Log\n")
        f.write(f"Started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
    
    process_rules()
